tasks:
  install-dependencies:
    name: Install Dependencies
    command: pip install --no-cache-dir -r requirements.txt && python -m ipykernel install --user --name=finrl-env && jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser
    triggeredBy:
      - postDevcontainerStart
