tasks:
  - name: Install Dependencies
    init: pip install --no-cache-dir -r requirements.txt && python -m ipykernel install --user --name=finrl-env
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser
ports:
  - port: 8888
    onOpen: notify
github:
  prebuilds:
    # Enable prebuilds for all branches and pull requests
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true # Add a check to GitHub for prebuild status
